//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExchangeRatesBot.Resourses {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MessageResourse {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageResourse() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExchangeRatesBot.Resourses.MessageResourse", typeof(MessageResourse).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I don&apos;t see a future, please specify a date less than {0}
        ///.
        /// </summary>
        internal static string DateMoreCurrentDate {
            get {
                return ResourceManager.GetString("DateMoreCurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telegram API Error:
        ///[{0}]
        ///[{1}].
        /// </summary>
        internal static string ErrorTelegram {
            get {
                return ResourceManager.GetString("ErrorTelegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As of {0}, the cost of 1 {1} is {2}.
        /// </summary>
        internal static string ExchangeRates {
            get {
                return ResourceManager.GetString("ExchangeRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send a message in the format &quot;Сurrency&quot; and &quot;date&quot;.
        ///Example &quot;/USD&quot; or &quot;USD 25.12.2021&quot;
        ///List of available currencies:
        ///{0}.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message contains the wrong date format. Use the &quot;/help&quot; command for more information.
        ///.
        /// </summary>
        internal static string IncorrectDate {
            get {
                return ResourceManager.GetString("IncorrectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The message format is incorrect. Use the &quot;/help&quot; command for more information..
        /// </summary>
        internal static string IncorrectFormatMessage {
            get {
                return ResourceManager.GetString("IncorrectFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive message type: {0} in chat {1}..
        /// </summary>
        internal static string ReceiveMessage {
            get {
                return ResourceManager.GetString("ReceiveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received type: {0} a &apos;{1}&apos; message in chat {2}.
        /// </summary>
        internal static string ReceiveMessageWithText {
            get {
                return ResourceManager.GetString("ReceiveMessageWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service is unavailable..
        /// </summary>
        internal static string ServiceIsUnavailableText {
            get {
                return ResourceManager.GetString("ServiceIsUnavailableText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi, I can show the exchange rate to hryvnia for any date. Use the &quot;/help&quot; command for more information..
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start listening for @{0}.
        /// </summary>
        internal static string StartBot {
            get {
                return ResourceManager.GetString("StartBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I only accept text messages. Use the &quot;/help&quot; command..
        /// </summary>
        internal static string UnknownUpdate {
            get {
                return ResourceManager.GetString("UnknownUpdate", resourceCulture);
            }
        }
    }
}
